config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  get 'l/:id', to: 'link_opener#open', as: :link_opener

  resources :links
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Link < ApplicationRecord
  URL_REGEXP = URI::DEFAULT_PARSER.make_regexp(%w[http https])

  validates :url, presence: true, format: {
    with: URL_REGEXP,
    message: "is not a valid URL" 
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/link_opener_controller.rb
class LinkOpenerController < ApplicationController
  def open
    link = Link.find_by(id: params[:id])
    if link
      redirect_to link.url, allow_other_host: true
    else
      render "link_not_found"
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_opener_helper.rb
module LinkOpenerHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkShortenerRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= javascript_importmap_tags %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/link_opener/open.html.erb
<h1>LinkOpener#open</h1>
<p>Find me in app/views/link_opener/open.html.erb</p>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <p>
    <strong>Url:</strong>
    <%= link.url %>
  </p>

</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Links</h1>

<div id="links">
  <% @links.each do |link| %>
    <%= render link %>
    <p>
      <%= link_to "Show this link", link %>
    </p>
  <% end %>
</div>

<%= link_to "New link", new_link_path %>

<%= react_component("HelloWorld", props: { name: "Fajar" }, prerender: false) %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<div>
  <%= link_to "Edit this link", edit_link_path(@link) %> |
  <%= link_to "Back to links", links_path %>

  <%= button_to "Destroy this link", @link, method: :delete %>
</div>